[package]
name = "tuntap"
version = "0.1.0"
authors = ["Thomas Knauth <thomas.knauth@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

libc = "0.2.2"
nix = "0.19.1"
ifstructs = "0.1.1"
